import { MdDashboard, MdKeyboardArrowRight } from "react-icons/md";
import {
  FaUsers,
  FaGraduationCap,
  FaNewspaper,
  FaDatabase,
  FaTools,
} from "react-icons/fa";
import { FiMail, FiSettings } from "react-icons/fi";
import { RiFilePaper2Line } from "react-icons/ri";
const sideBarItems = [
    {
      icon: MdDashboard,
      title: "Dashboard",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
    {
      icon: FaTools,
      title: "Setup",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
    {
      icon: FaUsers,
      title: "Manage Users",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
    {
      icon: FaGraduationCap,
      title: "Manage Students",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
    {
      icon: FaNewspaper,
      title: "Manage Competitions",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
    {
      icon: FaDatabase,
      title: "Administrations",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
    {
      icon: RiFilePaper2Line,
      title: "Reports",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
    {
      icon: FiMail,
      title: "Mail Templates",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
    {
      icon: FiSettings,
      title: "Settings",
      list: [
        "Awards",
        "Countries",
        "Grades",
        "Schools",
        "Organisations",
        "Topics",
        "Domains and Tags",
        "Currencies",
        "CSV Upload",
      ],
    },
  ];

  export default sideBarItems;